-- Problem 5
CREATE DATABASE Store

USE Store
GO

CREATE TABLE Cities(
	CityID INT IDENTITY,
	[Name] VARCHAR(50) NOT NULL,

	CONSTRAINT PK_City PRIMARY KEY (CityID)
);

CREATE TABLE Customers(
	CustomerID INT IDENTITY,
	[Name] VARCHAR(50) NOT NULL,
	Birthday DATE,
	CityID INT NOT NULL,

	CONSTRAINT PK_Customer PRIMARY KEY (CustomerID),
	CONSTRAINT FK_Customer_City FOREIGN KEY (CityID)
	REFERENCES Cities (CityID)
);

CREATE TABLE ItemTypes(
	ItemTypeID INT IDENTITY,
	[Name] VARCHAR(50) NOT NULL,

	CONSTRAINT PK_ItemType PRIMARY KEY (ItemTypeID),
);

CREATE TABLE Items(
	ItemID INT IDENTITY,
	[Name] VARCHAR(50) NOT NULL,
	ItemTypeID INT NOT NULL,

	CONSTRAINT PK_Item PRIMARY KEY (ItemID),
	CONSTRAINT FK_Item_ItemType FOREIGN KEY (ItemTypeID)
	REFERENCES ItemTypes (ItemTypeID)
);

CREATE TABLE Orders(
	OrderID INT IDENTITY,
	CustomerID INT NOT NULL,

	CONSTRAINT PK_Order PRIMARY KEY (OrderID),
	CONSTRAINT FK_Order_Customer FOREIGN KEY (CustomerID)
	REFERENCES Customers (CustomerID)
);

CREATE TABLE OrderItems(
	OrderID INT NOT NULL,
	ItemID INT NOT NULL,

	CONSTRAINT PK_OrderItem PRIMARY KEY(OrderID, ItemID),
	CONSTRAINT FK_OrderItem_Order FOREIGN KEY (OrderID) REFERENCES Orders(OrderID),
	CONSTRAINT FK_OrderItem_Item FOREIGN KEY (ItemID) REFERENCES Items(ItemID)
);